### ISSUE TITLE
Add wait timer for skip intros, recaps, start next episode, etc.

### ISSUE THREAD

**Issue by DestroyerXyz** [UniverseDevel/Netflex#1]

**Comment by DestroyerXyz** [comment]
First issue on such an amazing extension???

**Comment by UniverseDevel** [comment]
> First issue on such an amazing extension???

Hi, repository is public just few weeks. Somehow I didn't get a notification about new issue so I still need to tweak its settings, sorry for the delay.

Regarding the issue, could you elaborate why such a timer would be useful? I don't see an added value if you press skip button immediately or X seconds later (for some shows it would not be pressed at all as some of them have intros quite short)
