### ISSUE TITLE
Playback speed resets to 1.0x even if "Video features" is disabled

### ISSUE THREAD

**Issue by mariusi7** [UniverseDevel/Netflex#4]
With "Video features" all off and Video Speed Controller used to control playback speed, it made the latter no longer work on netflix.com: it resets to 1.0x on any change. This worked fine until a few days ago.
Using Netflix's own speedometer also doesn't work.
Tried changing the setting in NE to my preferred speed (without activating Video Features) but it still goes to 1.0x when using VSC.
With Video Features ON and a fixed speed, it does speed up, but I want to keep using VSC for speed (it's changeable during play).

**Comment by UniverseDevel** [comment]
Hello Marius,

In your review you don't mention that you use other extension to change speed and that features of this other extension started to misbehave, which is misleading and pointed me to a wrong path in debugging and made me look into my own speed rate feature.

You are correct and I recently did a change that I thought is needed and might have caused this. I will be releasing a fix shortly. Please be more accurate in your information next time.

**Comment by mariusi7** [comment]
Hello! I'm sorry for the confusion! And thanks for looking into it so quickly.

**Comment by UniverseDevel** [comment]
Extension version 6.4.1 has been released for Chrome, please update and let me know if it fixed your problem.

**Comment by mariusi7** [comment]
Yes, it did fix it. Thanks again
