### ISSUE TITLE
how to configure on latest firefox?

### ISSUE THREAD

**Issue by knockDOUGH** [UniverseDevel/Netflex#5]
I can't figure out how to configure the options. The extension description says:
> Options can be changed directly from Netflix™ page via extension status information bubble options button

But I don't see this when right-clicking the extension while on the Netflix page. Is it somewhere else?
![image](https://user-images.githubusercontent.com/3972414/116936769-22a1f300-ac1d-11eb-82bf-ffb2e5ba908d.png)

Left clicking the extension on the Netflix page just opens a new tab with the Netflix page.

I'm on Windows 10 64-bit. Firefox 88.0.

Thanks in advance.

**Comment by UniverseDevel** [comment]
Hi, try looking at screenshots on Add-on page like:

![248193](https://user-images.githubusercontent.com/47400898/116938481-25c3d000-ac6b-11eb-8653-86da95fd2c28.jpg)

**Comment by knockDOUGH** [comment]
ah i was looking from the extension manager window in firefox so didn't see screenshots. thanks for the quick reply, and it looks like a great add on! i'll explore more soon! thank you for your work - from one dev to another 😄
