### ISSUE TITLE
[Feature Request] Add video option for ultrawide display support (21:9 aspect ratio)

### ISSUE THREAD

**Issue by axeltrinidade** [UniverseDevel/Netflex#6]
Another minor video option that may also be quite useful would be the ability to display elapsed time

**Comment by UniverseDevel** [comment]
> Add video option for ultrawide display support

I will need more information what do you mean by that. 

Extension should work with whatever aspect ratio you have and in case you expect extension to adjust video stream output to be different aspect ratio, that's not possible by this extension.

> Another minor video option that may also be quite useful would be the ability to display elapsed time

I will have to look if this would be possible and reliable once I get back from vacation.

**Comment by axeltrinidade** [comment]
Clarification - 

Here is the default view:
![Screenshot (343)](https://user-images.githubusercontent.com/68217806/124352006-58faef00-dc1b-11eb-8ca5-d0185f99ff37.png)

Here is the other aspect, wherein it is automatically zoomed so as to allow a full screen experience without blank black bars:
![Screenshot (344)](https://user-images.githubusercontent.com/68217806/124352085-c575ee00-dc1b-11eb-99d4-8693dafd1148.png)


This here was done using another extension, [Better Netflix](https://gitlab.com/konstantin-mueller/better-netflix); I simply wish to increase Netflix Extended's functionality.

**Comment by UniverseDevel** [comment]
I see now, this might be possible but I will have to investigare as well as to test it somehow (I might need your help in case you own widescreen). I am on vacation till end of next week so once I will get back and have some free time, I will see what can be done.

**Comment by UniverseDevel** [comment]
You can probably try changes added with commit 873d2fa2eca08f7949e78137ba182a5d31f69640 or current master branch. They should contain both elapsed video time feature and aspect ratio feature. I did some basic tests if something did not get broken along the way and if changes are actually applied but final effect needs to be judged by someone that can actually use such feature.

**Comment by axeltrinidade** [comment]
Can you help me? I'm not sure how to test the changes

**Comment by UniverseDevel** [comment]
This update has been committed here but I haven't officially released an update yet, so only way to test it now is to download current repository and perform manual local test:

1. On Code page click green button "Code" and then "Download ZIP"
![1](https://user-images.githubusercontent.com/47400898/124390486-2836ba80-dcec-11eb-8be4-c947791fbcb1.png)

2. Extract downloaded ZIP into separate folder (name of the folder is not important but for guide purposes lets say this folder is on this path: C:\Users\\\<Your user name>\Downloads\Netflex-master)
3. Open new tab in Chrome and as URL insert chrome://extensions/
4. On this page you should see all extensions you have installed
5. Disable production Netflix Extended extension so they won't block each other out
6. In top right corner you should see "Developer mode" which by default is turned off, turn this option on
7. On left side three new buttons should pop up one being "Load unpacked", click this button and navigate to directory with unzipped extension (in this case it would be C:\Users\\\<Your user name>\Downloads\Netflex-master) and click "Select folder"
![2](https://user-images.githubusercontent.com/47400898/124390743-3a652880-dced-11eb-90c1-316648a354cf.png)

8. Now local version of this extension should be shown among other extensions, usually it is shown first
9. Note that this version will have some functions disabled like ratings, API key used by ratings is not included in GitHub repository. Also this extension is separate installation from official extension therefore no settings from official extension will be available and have to be manually configured if wanted. Usually for testing purposes this might not be necessary
10. Navigate to https://netflix.com or refresh already loaded tab with Netflix
11. Pick any video (optional, in case no video features are tested this step can be skipped)
12. In extension configuration check this option: Configuration > Debug > Simulate production environment. Netflix page should refresh and extension status icon should have a blue-ish ring around it. In case there is no Debug menu in configuration skip this step as extension already behaves like in production
![3](https://user-images.githubusercontent.com/47400898/124390754-4355fa00-dced-11eb-9eca-289ee85d5e3f.png)

13. Turn on features that you want to test, unless they are turned on by default
14. After testing navigate again to chrome://extensions/, find extension that you were testing and press "Remove" button to unload it. Enable production extension back so you will get official update for it via Chrome Extension Store
![4](https://user-images.githubusercontent.com/47400898/124390759-494bdb00-dced-11eb-8cd5-2049d82a3b25.png)


Features that you want to test are located:
- Configuration > Assistant > Show elapsed video time (should be on by default)
- Configuration > Video > Video features (this enables video settings to be applied, without this other video settings does not work)
  - Configuration > Video > Video aspect ratio (Switch to option 21:9)

**Comment by axeltrinidade** [comment]
Sorry for the delay. I use Firefox usually. Couldn't locate the .xpi file so I tested it on chromium Edge. Here's what I observed:

- The 'Show elapsed video time' feature worked flawlessly throughout.
- At first, I forgot to include step 12 (Simulate production environment) which caused the whole browser to go black when enabling video settings while still playing audio. After enabling step 12, it was fine. The 'Video aspect ratio' feature then worked as expected.
- In addition, may be too much to ask, but a manual zoom in/out button may be useful too, for finer adjustment.

Something unrelated: I noticed that before included step 12, there were a lot more video features like grayscale, brightness, hue, etc, which I had not known even while using the official release on Firefox. They disappeared when I enabled 'Simulate production environment', leaving only Video speed and Video aspect toggles.

**Comment by UniverseDevel** [comment]
Testing on FireFox has mostly the same steps except it is located on different page and instead of selecting folder you have to locate manifest.json in folder.

![image](https://user-images.githubusercontent.com/47400898/124584424-87174380-de54-11eb-985d-7cb765c2154d.png)

Step 12 is important especially because of the other video features. Unfortunately these video features completely break Edge browser. This is the reason video features are not in production but in dev/beta mode only. 

Manual zoom: I will see what I can do. This would be more complicated but it might be possible.

I have found quite a few bugs when I recently tested this new features so I will commit fixes once I got them sorted out.

**Comment by axeltrinidade** [comment]
Got it. Will continue using dev edition on firefox to check for other bugs too.

**Comment by UniverseDevel** [comment]
I pushed commit with fixes and manual zoom feature. You will have to download ZIP again, delete old extension folder and replace it with new and press "Reload" button on extension page in browser. It also might require Netflix page reload. In case the blue-ish ring around status icon is not present after this, you need to repeat step 12 again as well. FireFox also throws away extension settings for local extensions when they are unloaded so it might be needed to configure extension again.

I tested this changes of Edge (Chromium), Chrome, FireFox and they worked. With Opera browser I had a problem not related to extension and I had to contact Netflix support as they consider latest Opera browser as not supported. They had to escalate it further so there is no ETA when that will be fixed.

If you can try using manual zoom and let me know which value in it fits the best for 21:9 display so I might adjust the preset value for 21:9 aspect ratio. Currently Video zoom with value 134 is equal to what Video aspect ratio 21:9 does.

**Comment by axeltrinidade** [comment]
Thank you very much. Really appreciate how fast and well it's implemented.

134 for 21:9 works perfectly fine on my screen. I tried +-134 in multiple movies and none required any adjustment.

**Comment by UniverseDevel** [comment]
They managed to fix Opera playback and it works there as well. Meanwhile when I was waiting for them to fix Opera I reworked how all video features are applied to video and retested it on all browsers. It seems to be working and it is also much better implemented in my eyes. I will be publishing this changes by the end of the week. I also submitted a bug report to Microsoft regarding problem with their browser so hopefully they will fix it soon so hidden beta features could be published as well.

**Comment by axeltrinidade** [comment]
That's really nice to hear!
Looking forward to seeing the new implementation. The slider did seem a bit tedious to adjust. I didn't want to nitpick on it either, was happy you were able to implement the feature in the first place.

If there's anything I could help with, please let me know. Will definitely be recommending this extension to more people!

**Comment by UniverseDevel** [comment]
The slider in configuration is applied only once it actually changes not while it is being changed. That's due to how extension API works in general (asynchonus data saving). It would not work correctly if it would try to save values and apply then immediately, situations like value saved is different than value shown that is saved.

Anyway that reminds me that I added Video zoom to fast features that can be accessed via + icon in status bubble, this is part of rework that I did. If you set aspect ratio to manual you should see zoom among fast features and they apply changes immediatly even while itnis being adjusted. You can try that if you want, but changes are reset after each video so it can serve to fastly test/pinpoint value that you need.

For now I think tests are ok and I don't need any more. If you wish to test new changes, you sure can but when I will find enough time to publish this changes, it will go public.

**Comment by UniverseDevel** [comment]
Version 6.4.4 has been published for FireFox. You should be able to update production version of extension to start using new features. Have a nice day.
