### ISSUE TITLE
Skip intro don't work :(

### ISSUE THREAD

**Issue by grego31430** [UniverseDevel/Netflex#7]
Hi !
I have install this extension on Opéra GX for auto skip intro of netflix series.
But this don't work :'( 
I have this error in the console : 
![image](https://user-images.githubusercontent.com/22960003/131303881-c891d2ae-1001-4526-80b5-1abc65977b32.png)
What can I do ?

**Comment by UniverseDevel** [comment]
Hello, that's not error but a warning and its a bug in Chromium browsers where extensions ignore map files even if they are there. Can you please provide a screenshot of your Netflix player UI? You might have received a new UI that does not work with extension as it is experimental by Netflix and not everyone has received it (for example me, I did not received it and that's why it is not working).

**Comment by grego31430** [comment]
Yeah, there is the player ui I have :)
![image](https://user-images.githubusercontent.com/22960003/131307771-03cd9e97-f629-4920-b396-fc715bb3ec4c.png)

**Comment by UniverseDevel** [comment]
With cooperation from community members we managed to figure out few information about the new UI that is going around and extension does not work on.

This new UI is indeed part of testing and only few locations are participating at this moment. This means that still, until this UI reaches my account there is no way for me to fix this problem. This also means there is a workaround for this problem as testing on Netflix is optional but ON by default and you have to personally opt-out from it.

!!! This is how you can opt-out from testing on Netflix, visit page https://www.netflix.com/DoNotTest and turn testing participation OFF. Old UI should return to your account and extension should be working again. !!!

**Comment by grego31430** [comment]
I have disable the testing of NetFlix and this work !
Thank you so much ! :)

If you need more info about the new UI of Netflix I will give you what you need :)

**Comment by UniverseDevel** [comment]
> I have disable the testing of NetFlix and this work !
> Thank you so much ! :)
> 
> If you need more info about the new UI of Netflix I will give you what you need :)

Well, what I would need is hands-on access to it, so I could adjust extension to this new UI and test it. For that I need some account that has this UI and I don't think sharing your account is a good idea (but you can do whatever you want with it).

**Comment by UniverseDevel** [comment]
extension version 7.0.0 has just been publish and it fixes problem with extension not working on new Netflix UI. Shortly I will be releasing a patch 7.0.1 with some more bugfixes and polishing, so extension works a bit better on the new UI. But, at this time you can finally enjoy this extension on new Netflix UI again.
