### ISSUE TITLE
Netflix updated UI today

### ISSUE THREAD

**Issue by sklawren** [UniverseDevel/Netflex#8]
The UI while playing content was updated today. The green circle of the plugin is not showing up anymore when playing and it is no longer functioning (automatically skipping intros, etc.).

It does still show up in the header when browsing the library.

**Comment by UniverseDevel** [comment]
Hello, Netflix finally rolled out the new UI into production and I can get my hands on it. I am working on a fix.

**Comment by UniverseDevel** [comment]
Most of the stuff should be fixed in commit 36b3b3e26b3dd0741739e83eeb78c3c467ff8daa. Tomorrow, after work, I will perform more tests and will publish this as soon as I will be able.

**Comment by UniverseDevel** [comment]
Chrome and Firefox have already published new version, fixing extension on new UI. Can you confirm that it is now working?
